spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway:
            issuer-uri: http://localhost:8080/realms/hipermarket-reino
        registration:
          api-gateway:
            provider: api-gateway
            scope: openid
            client-id: market-gateway-client
            client-secret: bMqLTrN5CZd0JvPt8GFjDqb3GRljdt1l
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
server:
  port: 9090


logging:
    level:
        org:
            springframework:
                security: DEBUG